### ISSUE TITLE
[BUG] Script template length estimate doesn't accound for larger signatures.

### ISSUE THREAD

**Issue by msinkec** [bitcoin-sv/ts-sdk#109]
https://github.com/bitcoin-sv/ts-sdk/blob/55af7563047551699013cd6309dcb1afe3b88d81/src/script/templates/RPuzzle.ts#L134

Script templates assume signatures are 71 bytes long. They can be up to 73 bytes long.

**Comment by ty-everett** [comment]
True. Thanks for bringing this to our attention.

#122 also addresses this.
