### ISSUE TITLE
[BUG] - Curve import needs to be explicit for some reason

### ISSUE THREAD

**Issue by sirdeggen** [bitcoin-sv/ts-sdk#29]
## Bug Description

When attempting to use Curve class in code you have to specify the exact route rather than the general one.

## Steps to Reproduce

```javascript
import { PrivateKey, BigNumber, Curve } from '@bsv/sdk'
import CurveExplicit from '@bsv/sdk/primitives/curve'

console.log({ CurveExplicit: (new CurveExplicit()).g.toString() })

console.log({ Curve: (new Curve()).g.toString() })
```

## Expected Behavior

It should just work with Curve, I don't understand why the class isn't propagating through the exports properly.

```bash
{
  CurveExplicit: '0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798'
}
{
  Curve: '0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798'
}
```

## Actual Behavior

```bash
{
  CurveExplicit: '0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798'
}
TypeError: _sdk.Curve is not a constructor
```

## Stack Traces or Screenshots

```bash
{ Curve: undefined }
```

## Environment

`bsv/sdk@1.0.0`

**Comment by BraydenLangley** [comment]
I think that was fixed in an update recently. Try using version `@bsv/sdk: '1.0.6'`

**Comment by sirdeggen** [comment]
🤦‍♂️ thank you
