### ISSUE TITLE
[DISCUSSION] No Cache for Premimage on signing

### ISSUE THREAD

**Issue by brandonbryant12** [bitcoin-sv/ts-sdk#35]
## Summary

It looks like this does not implement a cache for the preimage of a transaction when signing
https://github.com/bitcoin-sv/ts-sdk/blob/93d934c25737e008d445e54a979bac273163e453/src/transaction/Transaction.ts#L310
https://github.com/bitcoin-sv/ts-sdk/blob/93d934c25737e008d445e54a979bac273163e453/src/script/templates/P2PKH.ts#L85

## Motivation

This was introduced in bsv v2 from moneybutton and is badly needed
https://github.com/moneybutton/bsv/blob/feab6d528c4013f6332b33169e771a95bc201285/lib/tx-builder.js#L39

If you need to consolidate many small utxos in a tx the signing time is really long

**Comment by sirdeggen** [comment]
Thanks for raising this Brandon. Definitely worth addressing. There was a comparison a few years back between bsv1, bsv2, nimble, and bsv-wasm. Worth doing a comparison table which includes this library and attempt to beat or at least match prior performance.

**Comment by sirdeggen** [comment]
**Performance Comparison**

| Library  | Load (ms) | Generate Keypair (ms) | Calculate Address (ms) | Sign Tx (ms) | Verify Signature (ms) | SHA256 (ms) |
| -------- | --------- | --------------------- | ---------------------- | ------------ | --------------------- | ----------- |
| nimble   | 9         | 1.6                   | 0                      | 1.7          | 6                     | 0           |
| bsv1     | 21        | 2                     | 0.2                    | 4.4          | 3.2                   | 0.1         |
| bsv2     | 25        | 1.4                   | 0.2                    | 2            | 5.2                   | 0.1         |
| bsv-wasm | 25        | 0.3                   | 0                      | 0.4          | 0.7                   | 0           |

**Comment by brandonbryant12** [comment]
> [source](https://github.com/runonbitcoin/nimble/blob/3f8e6318befd973c032861889c043a69daf79fce/README.md?plain=1#L132C1-L139C127)
> 
> **Performance Comparison**
> 
> Library	Load (ms)	Generate Keypair (ms)	Calculate Address (ms)	Sign Tx (ms)	Verify Signature (ms)	SHA256 (ms)
> nimble	9	1.6	0	1.7	6	0
> bsv1	21	2	0.2	4.4	3.2	0.1
> bsv2	25	1.4	0.2	2	5.2	0.1
> bsv-wasm	25	0.3	0	0.4	0.7	0

sign tx can be a bit misleading though, it would be better with another column that represented the time it takes to sign as the number of inputs grow.

afaik bsv is n^2 and bsv2 is n

**Comment by ty-everett** [comment]
The bulk of the time (around 28 of 30 ms on my machine) is spent on computing the signature with ECDSA, and only a very small amount is spent on computing the preimages or hashes. Because each preimage is for a different input, spending a different UTXO, the signatures for one preimage can't be cached for use on other preimages.

However, I've just released `1.0.12` with a change that enables parallelized signing of multiple inputs at once using the script templates, with `Promise.all`. I also added a test that spends 30 UTXOs in a transaction, which currently runs just over a second on my machine when dealing with the default P2PKH template.

Due to this new parallelization, new script templates can be created externally, which make use of tools like Web Workers in the browser or Node's Worker Threads for improved performance. This would offload the 30 ms ECDSA signature computation time onto another thread, all of which will now be executed in parallel instead of sequentially.

**Comment by brandonbryant12** [comment]
> The bulk of the time (around 28 of 30 ms on my machine) is spent on computing the signature with ECDSA, and only a very small amount is spent on computing the preimages or hashes. Because each preimage is for a different input, spending a different UTXO, the signatures for one preimage can't be cached for use on other preimages.
> 
> However, I've just released `1.0.12` with a change that enables parallelized signing of multiple inputs at once using the script templates, with `Promise.all`. I also added a test that spends 30 UTXOs in a transaction, which currently runs just over a second on my machine when dealing with the default P2PKH template.
> 
> Due to this new parallelization, new script templates can be created externally, which make use of tools like Web Workers in the browser or Node's Worker Threads for improved performance. This would offload the 30 ms ECDSA signature computation time onto another thread, all of which will now be executed in parallel instead of sequentially.

You can cache certain parts please check this for a reference https://github.com/moneybutton/bsv/blob/feab6d528c4013f6332b33169e771a95bc201285/lib/tx.js#L163C67-L163C76

makes a big difference when signing txs with a large number of inputs

**Comment by ty-everett** [comment]
Yes, there does seem to be significant computation for the preimage. When running my new test with a `spendCount` of 200, I see times around 20,328 ms. I've started caching the hashes of transactions in the Transaction class, and this reduces the time to 6,224 ms.

This seems to address the performance bottleneck, considering that it takes around 30 ms for an ECDSA signature to be computed. `30 * 200 = 6000`.

Previously, the time taken grew exponentially with the number of inputs. Now, I am able to sign 800 inputs in 25 seconds and 1600 in 52 seconds. While not perfectly linear, this is a significant improvement. I will publish the change with the cached TX hash.

**Comment by brandonbryant12** [comment]
> Yes, there does seem to be significant computation for the preimage. When running my new test with a `spendCount` of 200, I see times around 20,328 ms. I've started caching the hashes of transactions in the Transaction class, and this reduces the time to 6,224 ms.
> 
> This seems to address the performance bottleneck, considering that it takes around 30 ms for an ECDSA signature to be computed. `30 * 200 = 6000`.
> 
> Previously, the time taken grew exponentially with the number of inputs. Now, I am able to sign 800 inputs in 25 seconds and 1600 in 52 seconds. While not perfectly linear, this is a significant improvement. I will publish the change with the cached TX hash.

sweet

**Comment by ty-everett** [comment]
I'll close this for now, but feel free to re-open if issues persist.
