### ISSUE TITLE
[BUG] ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by domingotaal** [bitcoin-sv/ts-sdk#47]
## Bug Description

I wanted to sign a transaction directly on postman. It seems it should be possible to dynamically load a library as shown below but it is not working

## Steps to Reproduce
1. In postman create a dummy request with the following Pre-request script
pm.sendRequest("https://unpkg.com/@bsv/sdk", (err, res) => {
   //convert the response to text and save it as an environment variable
   pm.collectionVariables.set("bsv", res.text());
 
   // eval will evaluate the JavaScript code and initialize the min.js
   eval(pm.collectionVariables.get("bsv"));

  //use the library to sign a transaction and broadcast it via ARC
})

2. Send

## Expected Behavior

Library is loaded and you can use it to sign, broadcast via ARC, etc. 

## Actual Behavior

Reference error: exports is not defined

## Stack Traces or Screenshots

![image](https://github.com/bitcoin-sv/ts-sdk/assets/98329130/3e0c297c-650a-4323-8150-8d3b447bf567)

## Environment

- OS: Windows
- Node version: n/a
- `@bsv/sdk` version: 1.0.18

## Additional Information
Not sure if this is actually a bug as this is a very specific use case

**Comment by BraydenLangley** [comment]
@domingotaal you should be able to access the TS SDK modules from the unpkg cdn in a non-standard environment, such as Postman, once the above PR is merged and published to npmjs.

**Comment by BraydenLangley** [comment]
Currently the main entry point is set to commonJS, so you'll have to reference this bundled JS file:
https://unpkg.com/@bsv/sdk@1.1.28/dist/umd/bundle.js

Example usage in PostMan with a throwaway test private key:
<img width="1141" alt="Screenshot 2024-10-23 at 17 12 17" src="https://github.com/user-attachments/assets/cdb68f77-6ae3-429f-bded-87c68a82ada5">
