### ISSUE TITLE
[DISCUSSION] WoC defaults

### ISSUE THREAD

**Issue by sirdeggen** [bitcoin-sv/ts-sdk#61]
## Summary

Add whatsonchain as a default provider for a ChainTracker and an option for broadcaster along side ARC.

**Comment by sirdeggen** [comment]
Added default broadcaster too so that if you just do:

await tx.broadcast() it will use WoC.

**Comment by sirdeggen** [comment]
Acknowledging that ARC is preferable in a production env. WoC can be useful for demos without an api key.

**Comment by ty-everett** [comment]
Implemented by #67
