### ISSUE TITLE
[DISCUSSION] request for script templates for OP_RETURN and Metanet transactions

### ISSUE THREAD

**Issue by tiagolr** [bitcoin-sv/ts-sdk#68]
First of all congratulations on this library, very impressive stuff, cheers.

## Summary

It would be nice to have script templates to build OP_RETURN outputs and if possible Metanet txs aswell.

## Motivation

In old bsv library a very used function is `bsv.Script.buildSafeDataOut(data, encoding)` which basically outputs a script with asm `OP_FALSE OP_RETURN encoded_data` where data can be a string or an array of strings.  

I also use that function to build Metanet transactions by passing data such as `buildSafeDataOut(['meta', publicKey.toString(), parentTXID, subprotocol, ...metadata, data ])`. It would be nice to have a constructor for metanet outputs as well, though it can be easily built from an OP_RETURN constructor.

I am porting one of my applications to use this new sdk and this is a small feature that is missing.

I also considered forking this repo and sending a PR for these changes but the interface `ScriptTemplate` implements an unlock method which these outputs do not have, so I am not sure that would be the right approach.

Regards

## Additional References

https://github.com/moneybutton/bsv/blob/bsv-legacy/lib/script/script.js#L864

**Comment by ty-everett** [comment]
I think that, while these templates are useful, it makes sense to establish a new repository for common templates.

This keeps the core library clean while giving the community a place to contribute templates openly. Sometimes people may want to keep their templates proprietary, but the BSV Association can maintain an open and neutral place for common templates like these. Anyone can submit new ones and we'll just publish them under a `@bsv/templates` package.

Give me some time to set this up next week, and then I'll pull the two you've PR'd as the initial ones.

**Comment by tiagolr** [comment]
Makes sense, thanks for that.
By all means reject the PRs if they are not up to whats expected.
Let me know what you think of other PRs in the comments as well.
Best,

**Comment by tiagolr** [comment]
Still thinking if it wouldn't make sense to have an util like old bsv library has `buildSafeDataOut` https://github.com/moneybutton/bsv/blob/bsv-legacy/lib/script/script.js#L889 , its a commonly used function to build data outputs for txs. Would be nice to have something like that on the sdk without going through installing another library etc..

I don´t think there will be many submissions of transaction templates for now but if you think its best to have it as a separate repo I can undertand that, wouldn't be surprised if these two would be the only templates there for a while.

**Comment by ty-everett** [comment]
The templates repository now exists, and I've moved these initial two over there.

As the decoder is specific to OP_RETURN (and people who use OP_RETURN will already install the template), I've moved the decoder there too, so we can avoid shipping it for those who don't need it.

https://github.com/bitcoin-sv/ts-templates
